Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 198

Rails/SkipsModelValidations:
  Enabled: false

RSpec/MessageSpies:
  Exclude:
    - 'spec/**/*'


